### ISSUE TITLE
GA uses same data multiple times

### ISSUE THREAD

**Issue by 2sn** [conradtchan/starfit#46]
need to eliminate solutions with the same index occurring more than once

**Comment by 2sn** [comment]
fixed by #54

**Comment by 2sn** [comment]
@conradtchan I think this is fixing a bug that has been there since the beginning.

**Comment by conradtchan** [comment]
@2sn I think you're right. It was only detected by the new databases, because with the old database, a better solution could always be found with a combination of different models. Whereas with the new databases, the best fit lies outside of the space "spanned" by the models, so the best fit is achieved with one model.

**Comment by 2sn** [comment]
@conradtchan and they were very small data bases, so finding it by chance in GA is more likely.
